import Header from '@/components/common/Header';
import ReactQueryProviders from '@/hooks/useReactQuery';
import { authAPI } from '@/lib/axios/authApi';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  weight: '100 900',
  variable: '--font-pretendard',
  display: 'swap',
});

async function getUserInfo() {
  try {
    const { data } = await authAPI.get('/api/v1/mypage/banner');
    return data.data;
  } catch (error) {
    return null;
  }
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userInfo = await getUserInfo(); // 서버에서 데이터 패칭
  console.log('banner Info', userInfo);

  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="bg-BG">
        <ReactQueryProviders>
          <Header userInfo={userInfo} />
          <div className="m-auto max-w-[1340px]">{children}</div>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
