import Header from '@/components/common/Header';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  weight: '100 900',
  variable: '--font-pretendard',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="bg-BG">
        <Header />
        <div className="m-auto max-w-[1340px]">{children}</div>
      </body>
    </html>
  );
}
